name: name_workflows
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'trigger source'
        required: false
        default: 'cron-job.org'
jobs:
  name_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: name_steps_name
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          mkdir -p logs
          ACCOUNT_ID="$(basename "$GITHUB_REPOSITORY")"
          FILE="logs/${ACCOUNT_ID}.txt"
          echo "$(date '+%T') | konteks_satu=$(shuf -i100000-999999 -n1)" >> "$FILE"
          git add "$FILE"
          git commit -m "commit_satu"
          git push
          sleep $(( ( $(date +%s) % 3 ) + 1 ))
          echo "$(date '+%T') | konteks_dua=$(shuf -i1000-9999 -n1)" >> "$FILE"
          git add "$FILE"
          git commit -m "commit_dua"
          git push
          sleep $(( ( $(date +%s) % 3 ) + 1 ))
          NASHJ="$(sha256sum "$FILE" | awk '{print $1}')"
          echo "$(date '+%T') | konteks_tiga=$NASHJ" >> "$FILE"
          git add "$FILE"
          git commit -m "commit_tiga"
          git push
